### ISSUE TITLE
GPU weights

### ISSUE THREAD

**Issue by ramyaprabhu-alt** [XueFuzhao/OpenMoE#3]
Hey
I see that ColossalAI has the MoE layer implemented. Does this mean that OpenMoe's GPU compatible weights might be available somewhere?
If not, is there a way by which I can use the weights in the current repository on a GPU?
Thanks!

**Comment by XueFuzhao** [comment]
Hey, thanks for your interest!

I had a quick inference run on Colossal AI's implementation. It works. But I have no idea about their training part. You may ask the Colossal AI team for the latest status. (I'm not part of Colossal AI although I know many folk there)

I uploaded the OpenMoE-8B checkpoint after 890B tokens here:
https://huggingface.co/fuzhao/OpenMoE_8B/tree/main

Colossal AI also has the script to convert the Jax weights to Pytorch weights. You can use their script.

Btw, since the TPUs have become very limited these days, I cannot release the OpenMoE-8B after a lot of tokens very soon. This is the thing out of my control. Very sorry... I'm also very sad about that. :(
A kind note: the 790B tokens checkpoint used a typical next token prediction training objective after around 600B tokens, so just using the naive prompt would be fine.
Also, please note that the umT5 tokenizer usually prepends one start token before the query, do not forget that. You can see the inference script from Colossal AI. But their script uses the UL2 prompt template. You may need to modify it slightly.

We also noted that the large vocab size of my OpenMoE induces unstable (Nan) loss on multi-choice QA tasks during inference. But it works well on open-ended generation like triva_qa or machine translation. Comparing OpenMoE with other models on these Closed-set multi-choice tasks may introduce biased results. That is not the real OpenMoE :)

Also, to everyone, if you have enough resources, feel free to continue training OpenMoE checkpoint! Let's make OpenMoE community cool together!

**Comment by ramyaprabhu-alt** [comment]
I really appreciate your response! thank you
